# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-27 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuladi', models.CharField(max_length=200, verbose_name='Kullanıcı Adı')),
                ('takipci', models.CharField(max_length=200, verbose_name='Takipçi')),
                ('takip', models.CharField(max_length=200, verbose_name='Takip')),
                ('paylasim', models.CharField(max_length=200, verbose_name='Gönderi')),
            ],
        ),
    ]
