# Generated by Django 2.2.3 on 2019-07-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuladi', models.CharField(max_length=200, verbose_name='Kullanıcı Adı')),
                ('takipci', models.IntegerField(verbose_name='Takipçi')),
                ('takip', models.IntegerField(verbose_name='Takip')),
                ('paylasim', models.IntegerField(verbose_name='Gönderi')),
                ('kaydetmetarihi', models.DateTimeField(verbose_name='Kaydetme Tarihi')),
                ('prikuladi', models.CharField(max_length=200, verbose_name='Kullanıcı Adı')),
                ('profilresmi', models.CharField(max_length=200, verbose_name='Profil Resmi')),
            ],
        ),
    ]
