# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-02 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insta',
            name='kaydetmetarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Kaydetme Tarihi'),
            preserve_default=False,
        ),
    ]
