# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-02 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_insta_kaydetmetarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='insta',
            name='prikuladi',
            field=models.CharField(default=1, max_length=200, verbose_name='Kullanıcı Adı'),
            preserve_default=False,
        ),
    ]
