# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-03 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_insta_prikuladi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insta',
            name='kaydetmetarihi',
            field=models.DateTimeField(verbose_name='Kaydetme Tarihi'),
        ),
    ]
