# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-03 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_auto_20190703_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insta',
            name='kaydetmetarihi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Kaydetme Tarihi'),
        ),
    ]
