# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-04 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20190703_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='insta',
            name='profilresmi',
            field=models.CharField(default=1, max_length=200, verbose_name='Profil Resmi'),
            preserve_default=False,
        ),
    ]
